services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes: 
      - db_data:/var/lib/mysql                 # volumen persistente para MySQL
      - ./dump:/docker-entrypoint-initdb.d     # solo para importar .sql
    container_name: db
    networks:
      - app-network

  php-apache:
    build: Dockerfiles/php-apache/
    container_name: App_hackaton
    env_file:
      - .env
    depends_on:
      - db
    volumes: 
      - ./www/:/var/www/html
    ports:
      - ${PHP_PORT}:80
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_hackaton
    depends_on:
      - db
    restart: always
    ports:
      - ${PMA_PORT}:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_FORCE_SSL=false
    networks:
      - app-network
    volumes:
      - ./phpmyadmin_config/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro

networks:
  app-network:
    driver: bridge

volumes:
  db_data:


